insert into albumpais(nombre_pais, nacionalidad)
values ("Argentina", "Argentino");
insert into albumpais(nombre_pais, nacionalidad)
values ("Nigeria", "Nigeriano");
insert into albumpais(nombre_pais, nacionalidad)
values ("Bosnia", "Bosnia");
insert into albumpais(nombre_pais, nacionalidad)
values ("Iran", "Irani");


INSERT INTO figuritas(codigoalbum, pose, nombrejugador, posicion, direccionimagen, dificultad)
values (1, 2, "Sergio Romero", "Portero", "sergioromero", "Facil"),
       (1, 3, "Ever Vanega", "Centrocampista", "evervanega", "Dificil"),
       (1, 4, "Ezequiel Garay", "Defensa", "ezequielgaray", "Facil"),
       (1, 5, "Hugo Campagnaro", "Defensa", "hugocampagnaro", "Dificil"),
       (1, 6, "Pablo Zabaleta", "Defensa", "pablozabaleta", "Facil"),
       (1, 7, "Fernando Gago", "Centrocampista", "fernandogago", "Dificil"),
       (1, 8, "Lucas Biglia", "Centrocampista", "lucasbigilia", "Facil"),
       (1, 9, "Ángel Di María", "Centrocampista", "angeldimaria", "Dificil"),
       (1, 10, "Gonzalo Higuaín", "Delantero", "gonzalohiguain", "Facil"),
       (1, 11, "Lionel Messi", "Delantero", "lionelmessi", "Dificil"),
       (1, 12, "Maximiliano Rodríguez", "Centrocampista", "maxirodriguez", "Facil"),
       (1, 13, "Javier Mascherano", "Centrocampista", "javiermascherano", "Dificil"),
       (1, 14, "Marcos Rojo", "Defensa", "marcosrojo", "Facil"),
       (1, 15, "Federico Fernández", "Defensa", "federicofernandez", "Dificil"),
       (1, 16, "Rodrigo Palacio", "Delantero", "rodrigopalacio", "Facil"),
       (1, 17, "Sergio Agüero", "Delantero", "sergioaguero", "Dificil"),
       (1, 18, "Ezequiel Lavezzi", "Delantero", "ezequiellavezzi", "Facil"),
       (1, 1, "Equipo Argentino", "Equipo Argentino", "equipoargentina", "Facil"),
       (2, 1, "Equipo Bosnia", "Equipo Bosnia", "equipobosnia", "Facil"),
       (2, 2, "Asmir Begovic", "Portero", "asmirbegovic", "Dificil"),
       (2, 3, "Emir Spahic", "Defensa", "emirspahic", "Facil"),
       (2, 4, "Avdija Vršajevic", "Defensa", "avdijavrsajevic", "Facil"),
       (2, 5, "Ermin Bicakcic", "Defensa", "emirbicakcic", "Facil"),
       (2, 6, "Toni Šunjic", "Defensa", "tonisunjic", "Dificil"),
       (2, 7, "Sead Kolašinac", "Defensa", "seadkolasinac", "Facil"),
       (2, 8, "Senad Lulic", "Centrocampista", "senadlulic", "Facil"),
       (2, 9, "Senijad Ibricic", "Centrocampista", "senijadibricic", "Facil"),
       (2, 10, "Mensur Mujdža", "Centrocampista", "mensurmujdza", "Dificil"),
       (2, 11, "Haris Medunjanin", "Centrocampista", "harismedunjanin", "Dificil"),
       (2, 12, "Zvjezdan Misimovic", "Centrocampista", "zvjezdanmisimovic", "Dificil"),
       (2, 13, "Miralem Pjanic", "Centrocampista", "miralempjanic", "Facil"),
       (2, 14, "Sejad Salihovic", "Centrocampista", "sejadsalihovic", "Facil"),
       (2, 15, "Adnan Zahirovic", "Centrocampista", "adnanzahirovic", "Facil"),
       (2, 16, "Izet Hajrovic", "Centrocampista", "izethajrovic", "Facil"),
       (2, 17, "Vedad Ibiševic", "Delantero", "vedadibisevic", "Facil"),
       (2, 18, "Edin Dzeko", "Delantero", "edindzeko", "Dificil"),
       (3, 1, "Equipo Iran", "Equipo Iran", "equipoiran", "Dificil"),
       (3, 2, "Daniel Davari", "Portero", "danieldavari", "Facil"),
       (3, 3, "Jalal Hosseini", "Defensa", "jalalhosseini", "Dificil"),
       (3, 4, "Khosro Heydari", "Delantero", "khosroheydari", "Facil"),
       (3, 5, "Hossein Mahini", "Defensa", "hosseinmahini", "Dificil"),
       (3, 6, "Pejman Montazeri", "Defensa", "pejmanmontazeri", "Facil"),
       (3, 7, "Ehsan Hajsafi", "Centrocampista", "ehsanhajsafi", "Facil"),
       (3, 8, "Hashem Beikzadeh", "Defensa", "hashembeikzadeh", "Facil"),
       (3, 9, "Amir Sadeghi", "Defensa", "amirhosseinsadeghi", "Facil"),
       (3, 10, "Javad Nekounam", "Centrocampista", "javadnekounam", "Facil"),
       (3, 11, "Andranik Teymourian", "Centrocampista", "andranikteymourian", "Dificil"),
       (3, 12, "Mojtaba Jabbari", "Delantero", "mojtabajabbari", "Facil"),
       (3, 13, "Masoud Shojaei", "Delantero", "masoudshojaei", "Dificil"),
       (3, 14, "Ashkan Dejagah", "Delantero", "ashkandejagah", "Facil"),
       (3, 15, "Reza Ghoochannejhad", "Delantero", "rezagroochannejhad", "Facil"),
       (3, 16, "Grolamreza Rezaei", "Delantero", "grolamrezarezaei", "Facil"),
       (3, 17, "Karim Ansarifard", "Delantero", "karimansarifard", "Facil"),
       (3, 18, "Mohammad Khalatbari", "Delantero", "mohammadkhalatbari", "Dificil"),
       (4, 1, "Equipo Nigeria", "Equipo Nigeria", "equiponigeria", "Dificil"),
       (4, 2, "Vincent Enyeama", "Portero", "vincentenyeama", "Facil"),
       (4, 3, "Joseph Yobo", "Defensa", "josephyobo", "Facil"),
       (4, 4, "Efe Ambrose", "Defensa", "efeambrose", "Facil"),
       (4, 5, "Godfrey Oboabona", "Defensa", "godfreyoboabona", "Facil"),
       (4, 6, "Azubuike Egwuekwe", "Defensa", "azubuikeegwuekwe", "Dificil"),
       (4, 7, "Kenneth Omeruo", "Defensa", "kennethomeruo", "Facil"),
       (4, 8, "John Ogu", "N/C", "johnogu", "Facil"),
       (4, 9, "Ogenyi Onazi", "Centrocampista", "ogenyionazi", "Facil"),
       (4, 10, "Sunday Mba", "N/C", "sundaymba", "Facil"),
       (4, 11, "Victor Moses", "Delantero", "victormoses", "Dificil"),
       (4, 12, "Nnamdi Oduamadi", "Delantero", "nnamdioduamadi", "Dificil"),
       (4, 13, "Ahmed Musa", "Delantero", "ahmedmusa", "Facil"),
       (4, 14, "Ideye Brown ", "N/C", "ideyebrown", "Facil"),
       (4, 15, "Shola Ameobi", "Delantero", "sholaameobi", "Dificil"),
       (4, 16, "Emmanuel Emenike", "Delantero", "emmanuelemenike", "Dificil"),
       (4, 17, "Elderson Echiéjilé", "Defensa", "eldersonechiejile", "Dificil"),
       (4, 18, "Mikel John Obi", "N/C", "mikeljohnobi", "Dificil");


insert into combos(nombrecombo, dificultadcombo, imagencombo)
values ("Super Argentina", "Dificil", "nin"),
       ("Argentina Alpha", "Dificil", "nin"),
       ("Argentina Beta", "Facil", "nin"),
       ("Super Nigeria", "Dificil", "nin"),
       ("Nigeria Alpha", "Dificil", "nin"),
       ("Nigeria Beta", "Facil", "nin"),
       ("Super Bosnia", "Dificil", "nin"),
       ("Bosnia Alpha", "Dificil", "nin"),
       ("Bosnia Beta", "Facil", "nin"),
       ("Super Iran", "Dificil", "nin"),
       ("Iran Alpha", "Dificil", "nin"),
       ("Iran Beta", "Facil", "nin");


INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(2, 7);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(3, 7);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(2, 8);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(3, 8);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(2, 9);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(3, 9);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(3, 10);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(3, 11);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(3, 12);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(1, 13);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(2, 13);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(1, 14);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(2, 14);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(1, 15);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(2, 15);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(1, 16);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(1, 17);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(1, 18);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(4, 19);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(4, 20);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(4, 21);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(4, 22);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(6, 22);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(4, 23);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(6, 23);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(4, 24);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(6, 24);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(5, 25);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(6, 25);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(5, 26);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(6, 26);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(5, 27);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(6, 27);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(5, 28);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(5, 29);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(5, 30);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(7, 37);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(7, 38);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(9, 38);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(7, 39);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(7, 40);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(7, 41);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(7, 42);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(8, 43);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(8, 44);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(8, 45);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(8, 46);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(8, 47);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(8, 48);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(9, 49);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(9, 50);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(9, 51);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(9, 52);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(9, 53);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(10, 55);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(10, 56);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(10, 57);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(10, 58);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(10, 59);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(10, 60);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(11, 61);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(11, 62);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(11, 63);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(11, 64);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(11, 65);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(11, 66);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(12, 67);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(12, 68);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(12, 69);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(12, 70);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(12, 71);
INSERT INTO `figuritascombo` (`codigocombo`, `codigofigurita`) VALUES(12, 72);



INSERT INTO figuritascombos
values (1, 18),
       (1, 17),
       (1, 16),
       (1, 15),
       (1, 14),
       (1, 13),
       (2, 15),
       (2, 14),
       (2, 13),
       (2, 9),
       (2, 8),
       (2, 7),
       (3, 12),
       (3, 11),
       (3, 10),
       (3, 9),
       (3, 8),
       (3, 7),
       (4, 19),
       (4, 20),
       (4, 21),
       (4, 22),
       (4, 23),
       (4, 24),
       (5, 25),
       (5, 26),
       (5, 27),
       (5, 28),
       (5, 29),
       (5, 30),
       (6, 22),
       (6, 23),
       (6, 24),
       (6, 25),
       (6, 26),
       (6, 27),
       (7, 37),
       (7, 38),
       (7, 39),
       (7, 40),
       (7, 41),
       (7, 42),
       (8, 43),
       (8, 44),
       (8, 45),
       (8, 46),
       (8, 47),
       (8, 48),
       (9, 49),
       (9, 50),
       (9, 51),
       (9, 52),
       (9, 53),
       (9, 38),
       (10, 55),
       (10, 56),
       (10, 57),
       (10, 58),
       (10, 59),
       (10, 60),
       (11, 61),
       (11, 62),
       (11, 63),
       (11, 64),
       (11, 65),
       (11, 66),
       (12, 67),
       (12, 68),
       (12, 69),
       (12, 70),
       (12, 71),
       (12, 72);

INSERT INTO preguntas(pregunta, niveldificultad)
VALUES ("¿Cuál de los siguientes equipos no se encuentra en el grupo a?", "facil"),
       ("¿En donde se hizo la inauguración?", "facil"),
       ("¿Dónde se juega la final del mundial?", "facil"),
       ("¿Cuál de los siguientes jugadores no se encuentra en el plantel argentino?", "facil"),
       ("¿En que año gano Argentina, por ultima vez, un mundial?", "facil"),
       ("¿Quién gano el último mundial en África?", "facil"),
       ("¿Cual fue el último mundial ganado por Alemania?", "dificil"),
       ("¿Cuál de los siguientes equipos fue el primer eliminado del actual mundial?", "facil"),
       ("¿Cuál fue la primera sede del mundial de futbol?", "dificil"),
       ("¿Cuál fue el resultado del partido España-Holanda?", "facil"),
       ("¿Qué grupo tiene en todas sus banderas el color blanco y en ninguna amarillo?", "dificil"),
       ("¿Qué fecha se juega la final de la copa del mundo?", "dificil"),
       ("¿Cuál fue el resultado del partido Argentina-Bosnia?", "facil"),
       ("En el mundial de 2002 organizado entre Japón y corea del sur ¿Dónde se jugo la final?", "dificil"),
       ("¿Cuál fue la lesión que sufrió el arquero Argentino Nery Pumpido en 1990?", "dificil"),
       ("¿Cuántos países no ganaron la copa siendo cede del mundial?", "dificil"),
       ("¿Cuántos países ganaron la copa siendo cede del mundial?", "dificil"),
       ("¿Qué eligió la selección de Japón como mascota?", "facil"),
       ("¿Qué colores tiene la bandera de Grecia?", "dificl"),
       ("¿Cuántos años tenia el jugador mas joven de los mundiales?", "dificil"),
       ("¿Cuántos países integran el mundial?", "facil"),
       ("¿Cuántos partidos de la final terminaron en penales? ", "dificil"),
       ("¿Quién o quienes tienen el record de la mayor cantidad de goles en un mundial?", "dificil"),
       ("¿Qué equipo fue el responsable del 10 a 1 contra El Salvador en 1982?", "dificil"),
       ("¿Qué país tiene el record de quedar en 3er puesto?", "dificil"),
       ("¿Cuál es la cantidad de goles en contra efectuados en los mundiales?", "dificil"),
       ("¿Quién gano el balón de oro en el mundial de Sudáfrica?", "facil"),
       ("¿Cuántos trofeos se entregan en la copa del mundo?", "facil"),
       ("¿Cando se implemento el ojo de halcón en el mundial?", "facil"),
       ("¿Cuántos grupos hay en un mundial?", "facil"),
       ("¿Cuántas pelotas hay en juego en un partido de futbol?", "facil"),
       ("¿Cuántos jueces hay en un partido de futbol?", "facil"),
       ("¿Cuándo es penal?", "facil"),
       ("¿Cuántos jugadores hay en un partido de futbol?", "facil"),
       ("¿Quién mordió al jugador italiano en la ronda de eliminatorias?", "dificil"),
       ("¿Quién provocó el famoso cabezazo en el mundial de Alemania?", "dificil"),
       ("¿Quién hizo la canción del mundial 2014?", "facil"),
       ("¿A que país pertenece el tema del mundial mas famoso?", "dificil"),
       ("¿Cuántos cambios se pueden hacer en un partido?", "facil"),
       ("¿Cuántos equipos Han participado en la copa del mundo? ", "dificil"),
       ("¿Quién fue el autor del gol llamado la mano de dios?", "facil"),
       ("¿Qué es una vuvuzela?", "facil"),
       ("¿Cómo se llamo la mascota del mundial de 1978?", "dificil"),
       ("¿Cómo se llama la pelota del mundial 2014?", "dificil"),
       ("¿De que marca son los botines que usa Messi en el mundial 2014?", "facil"),
       ("¿Cuál es el número de la camiseta de Higuain?", "dificil"),
       ("¿Cómo se llama la asociación que organiza el mundial?", "facil"),
       ("¿Qué país invento el aerosol de espuma que se utiliza en los tiros libres?", "facil"),
       ("¿Cuál es la cancha con mayor capacidad del mundial de Brasil?", "dificil"),
       ("¿Quién metió el primer gol olímpico en un mundial?", "dificil"),
       ("¿En cuantos Mundiales participo Messi?", "facil"),
       ("¿En que grupo esta Argentina?", "facil"),
       ("¿Qué colores tiene la bandera de Japón?", "facil"),
       ("¿Contra que equipo se enfrenta Argentina en octavos de final?", "facil"),
       ("¿Con que numero de camiseta juega Messi?", "facil"),
       ("¿En que equipo juega Ronaldo?", "facil"),
       ("¿Cuál de los siguientes no equipos no paso a octavos de final?", "facil"),
       ("¿Qué animal representa la mascota del mundial 2014?", "facil"),
       ("¿Cómo se llama el arquero de la selección argentina?", "facil"),
       ("¿Cada cuantos años se realizan los mundiales de futbol?", "facil");

INSERT INTO respuestas
VALUES (1, "Brasil", false),
       (1, "Mexico", false),
       (1, "Argentina", true),
       (1, "Camerun", false),
       (1, "Ninguno de los anteriores", true),
       (2, "San Pablo", true),
       (2, "Rio de Janeiro", false),
       (2, "Porto Alegre", false),
       (2, "Fortaleza", false),
       (2, "Curitiba", false),
       (3, "Belo Horizonte", false),
       (3, "Brasilia", false),
       (3, "Fortaleza", false),
       (3, "Rio de Janeiro", true),
       (3, "Porto Alegre", false),
       (4, "Agüero", false),
       (4, "Messi", false),
       (4, "Rojo", false),
       (4, "Higuain", false),
       (4, "Tevez", true),
       (5, "1988", false),
       (5, "1986", true),
       (5, "1996", false),
       (5, "1978", false),
       (5, "1987", false),
       (6, "Camerun", false),
       (6, "Brasil", false),
       (6, "España", true),
       (6, "Paises Bajos", false),
       (6, "Ninguno de los anteriores", false),
       (7, "1991", false),
       (7, "1990", true),
       (7, "1987", false),
       (7, "1989", false),
       (7, "1974", false),
       (8, "España", true),
       (8, "Costa Rica", false),
       (8, "Italia", false),
       (8, "Croacia", false),
       (8, "Inglaterra", false),
       (9, "Suiza", false),
       (9, "Francia", false),
       (9, "Italia", false),
       (9, "Brasil", false),
       (9, "Uruguay", true),
       (10, "2 a 0", false),
       (10, "3 a 4", false),
       (10, "1 a 5", true),
       (10, "0 a 0", false),
       (10, "2 a 3", false),
       (11, "F", false),
       (11, "D", true),
       (11, "H", false),
       (11, "E", false),
       (11, "C", false),
       (12, "10 de julio", false),
       (12, "12 de julio", false),
       (12, "14 de julio", false),
       (12, "13 de julio", true),
       (12, "9 de julio", false),
       (13, "1 a 0", false),
       (13, "1 a 1", false),
       (13, "2 a 1", true),
       (13, "2 a 2", false),
       (13, "3 a 2", false),
       (14, "Tokyo", false),
       (14, "Yokohama", true),
       (14, "seul", false),
       (14, "Kyoto", false),
       (14, "Deagu", false),
       (15, "Fractura de tivia y perone", true),
       (15, "Fisura de costilla", false),
       (15, "Fractura de clavicula", false),
       (15, "Perdio un dedo", false),
       (15, "Fractura de muñeca", false),
       (16, "15", false),
       (16, "10", false),
       (16, "9", false),
       (16, "13", true),
       (16, "8", false),
       (17, "9", false),
       (17, "6", true),
       (17, "5", false),
       (17, "4", false),
       (17, "Ninguno ", false),
       (18, "Una planta", false),
       (18, "Un animal", false),
       (18, "Un pokemon", true),
       (18, "Un edificio", false),
       (18, "No tiene mascota", false),
       (19, "Blanco y azul", true),
       (19, "Blanco y verde", false),
       (19, "Blanco y rojo", false),
       (19, "Amarillo y rojo", false),
       (19, "Verde y amarillo", false),
       (20, "21", false),
       (20, "20", false),
       (20, "18", false),
       (20, "16", false),
       (20, "17", true),
       (21, "36", false),
       (21, "24", false),
       (21, "32", true),
       (21, "38", false),
       (21, "28", false),
       (22, "5", false),
       (22, "4", false),
       (22, "3", false),
       (22, "2", true),
       (22, "Ninguno", false),
       (23, "Ronaldo", false),
       (23, "Ronaldo-Miroslav", true),
       (23, "Pelé", false),
       (23, "Batistuta-Pelé", false),
       (23, "Ninguno de estos", false),
       (24, "El Salvador", false),
       (24, "Portugal", false),
       (24, "Ungria", true),
       (24, "Alemaña", false),
       (24, "Ninguno de estos", false),
       (25, "Brasil", false),
       (25, "Alemaña", true),
       (25, "Argentina", false),
       (25, "Costa Rica", false),
       (25, "Corea del sur", false),
       (26, "26", false),
       (26, "35", false),
       (26, "20", false),
       (26, "36", true),
       (26, "40", false),
       (27, "Pirlo", false),
       (27, "Maradona", false),
       (27, "Forlán", true),
       (27, "Virlo", false),
       (27, "Messi", false),
       (28, "7", false),
       (28, "4", false),
       (28, "3", false),
       (28, "6", true),
       (28, "5", false),
       (29, "En este mundial", true),
       (29, "En Sudafrica", false),
       (29, "En Alemaña", false),
       (29, "En españa", false),
       (29, "En Francia", false),
       (30, "4", false),
       (30, "8", true),
       (30, "6", false),
       (30, "2", false),
       (30, "Ninguno", false),
       (31, "5", false),
       (31, "6", false),
       (31, "32", false),
       (31, "2", false),
       (31, "1", true),
       (32, "1", false),
       (32, "2", false),
       (32, "3", true),
       (32, "5", false),
       (32, "7", false),
       (33, "Falta en el area", true),
       (33, "Una falta normal", false),
       (33, "Se agarra la pelota con la mano ", false),
       (33, "Se cabecea a otro jugador", false),
       (33, "Se muerde a otro jugador", false),
       (34, "25", false),
       (34, "11", false),
       (34, "15", false),
       (34, "22", true),
       (34, "24", false),
       (35, "Suarez", true),
       (35, "Forlán", false),
       (35, "Muslera", false),
       (35, "Cavani", false),
       (35, "Godín", false),
       (36, "Pelé", false),
       (36, "Suarez", false),
       (36, "Zidane", true),
       (36, "Pirlo", false),
       (36, "Maradona", false),
       (37, "Tan bionica", false),
       (37, "Pitbull y Yenifer Lopez", true),
       (37, "Ricki Martin", false),
       (37, "Wisin y Yandel", false),
       (37, "La Mona Jimenez", false),
       (38, "Chile", false),
       (38, "Argentina", false),
       (38, "Portugal", false),
       (38, "Italia", true),
       (38, "Japon-Corea del Sur", false),
       (39, "Se arregla antes del partido", false),
       (39, "5", false),
       (39, "4", false),
       (39, "2", false),
       (39, "3", true),
       (40, "100", false),
       (40, "80", false),
       (40, "76", true),
       (40, "96", false),
       (40, "40", false),
       (41, "Pelé", false),
       (41, "Harry Potter", false),
       (41, "Maradona", true),
       (41, "Ronaldo", false),
       (41, "Lor baldomero", false),
       (42, "Un tambor", false),
       (42, "Una corneta", true),
       (42, "Una trompeta", false),
       (42, "Una pelota", false),
       (42, "Una parte del cuerpo huano", false),
       (43, "Juanito", false),
       (43, "Zakumi", false),
       (43, "Ciao", false),
       (43, "Footix", false),
       (43, "Gauchito", true),
       (44, "Fevernova", false),
       (44, "Brazuca", true),
       (44, "Tricolore", false),
       (44, "Crack", false),
       (44, "Tango", false),
       (45, "Nike", false),
       (45, "Olympikus", false),
       (45, "Adidas", true),
       (45, "Puma", false),
       (45, "Topper", false),
       (46, "10", false),
       (46, "9", true),
       (46, "22", false),
       (46, "19", false),
       (46, "11", false),
       (47, "AFA", false),
       (47, "FAFA", false),
       (47, "FAFI", false),
       (47, "FIFA", true),
       (47, "IFA", false),
       (48, "Argentina", true),
       (48, "Brasil", false),
       (48, "Alemania", false),
       (48, "Inglaterra", false),
       (48, "Mexico", false),
       (49, "Fonte Nova", false),
       (49, "Maracana", true),
       (49, "Pernambuco", false),
       (49, "Amazônia", false),
       (49, "Das Dunas", false),
       (50, "Adan Godoy", false),
       (50, "Sergio Valdez", false),
       (50, "Marcos Coll", true),
       (50, "Oscar Rossi", false),
       (50, "Marcelo Pagani", false),
       (51, "5", false),
       (51, "Niguno", false),
       (51, "4", false),
       (51, "3", true),
       (51, "2", false),
       (52, "Grupo B", false),
       (52, "Grupo G", false),
       (52, "Grupo F", true),
       (52, "Grupo H", false),
       (52, "Grupo D", false),
       (53, "Blanco y rojo", true),
       (53, "Verde y amarillo", false),
       (53, "Banco y celeste", false),
       (53, "Amarillo y rojo", false),
       (53, "Azul y rojo", false),
       (54, "Grecia", false),
       (54, "Nigeria", false),
       (54, "Francia", false),
       (54, "Suiza", true),
       (54, "Brasil", false),
       (55, "22", false),
       (55, "10", true),
       (55, "11", false),
       (55, "9", false),
       (55, "17", false),
       (56, "Colombia", false),
       (56, "Alemania", false),
       (56, "Brasil", false),
       (56, "Mexico", false),
       (56, "Portugal", true),
       (57, "Argentina", false),
       (57, "Portugal", true),
       (57, "Nigeria", false),
       (57, "Mexico", false),
       (57, "Colombia", false),
       (58, "Mulita", false),
       (58, "Coati", false),
       (58, "Perro", false),
       (58, "Armadillo", true),
       (58, "Puercoespin", false),
       (59, "Pablo Carrizo", false),
       (59, "Carlos Abbondanzieri", false),
       (59, "Sergio Romero", true),
       (59, "Guillermo Ochoa", false),
       (59, "Mariano Andújar", false),
       (60, "2", false),
       (60, "6", false),
       (60, "5", false),
       (60, "4", true),
       (60, "3", false);