/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jmg.mundial.view;

import com.jmg.mundial.controller.FiguritaCanjeController;
import com.jmg.mundial.model.Figurita;
import org.edisoncor.gui.panel.PanelImage;

import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Jonathan
 */
public class VCANJE extends javax.swing.JFrame {

    VJUGARPOR ventanajugarpor;
    Figurita figuritarepetida = null;
    Figurita figuritacanje = null;

    public VCANJE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        cmdVolver = new javax.swing.JButton();
        cmdCanje = new javax.swing.JButton();
        cboRepetido = new javax.swing.JComboBox();
        cbofaltante = new javax.swing.JComboBox();
        lblfigurita1 = new org.edisoncor.gui.panel.PanelImage();
        lblfigurita2 = new org.edisoncor.gui.panel.PanelImage();
        lblDificultadRepetido = new javax.swing.JLabel();
        lblDificultadcanje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/FIGURAS/CMDCANJEAR.jpg"))); // NOI18N

        cmdVolver.setText("VOLVER");
        cmdVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVolverActionPerformed(evt);
            }
        });

        cmdCanje.setText("CANJEAR");
        cmdCanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCanjeActionPerformed(evt);
            }
        });

        cboRepetido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRepetidoItemStateChanged(evt);
            }
        });

        cbofaltante.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbofaltanteItemStateChanged(evt);
            }
        });

        lblfigurita1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout lblfigurita1Layout = new javax.swing.GroupLayout(lblfigurita1);
        lblfigurita1.setLayout(lblfigurita1Layout);
        lblfigurita1Layout.setHorizontalGroup(
                lblfigurita1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        lblfigurita1Layout.setVerticalGroup(
                lblfigurita1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        lblfigurita2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout lblfigurita2Layout = new javax.swing.GroupLayout(lblfigurita2);
        lblfigurita2.setLayout(lblfigurita2Layout);
        lblfigurita2Layout.setHorizontalGroup(
                lblfigurita2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 142, Short.MAX_VALUE)
        );
        lblfigurita2Layout.setVerticalGroup(
                lblfigurita2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 187, Short.MAX_VALUE)
        );

        lblDificultadRepetido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblDificultadcanje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(cmdVolver))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelImage1Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cmdCanje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(lblDificultadRepetido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(lblfigurita1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(cboRepetido, javax.swing.GroupLayout.Alignment.LEADING, 0, 144, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblfigurita2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(cbofaltante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(lblDificultadcanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                .addGap(30, 30, 30))
        );
        panelImage1Layout.setVerticalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbofaltante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboRepetido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblfigurita2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblfigurita1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDificultadRepetido)
                                        .addComponent(lblDificultadcanje))
                                .addGap(18, 18, 18)
                                .addComponent(cmdCanje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdVolver)
                                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCanjeActionPerformed
        try {
            FiguritaCanjeController.canjearfigurita(this.ventanajugarpor.getPartida(), this.figuritarepetida, this.figuritacanje);
            this.inicializarventanacanje(this.ventanajugarpor);
            this.repaint();
            new FiguritaCanjeController().inicializarCombosCanje(this);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VCANJE.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmdCanjeActionPerformed

    private void cboRepetidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRepetidoItemStateChanged
        try {
            FiguritaCanjeController e = new FiguritaCanjeController();
            e.inicializarFiguritas(this, false, (String) this.cboRepetido.getSelectedItem());
            this.repaint();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VCANJE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboRepetidoItemStateChanged

    private void cbofaltanteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbofaltanteItemStateChanged
        try {
            FiguritaCanjeController e = new FiguritaCanjeController();
            e.inicializarFiguritas(this, true, (String) this.cbofaltante.getSelectedItem());
            this.repaint();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VCANJE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbofaltanteItemStateChanged

    private void cmdVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVolverActionPerformed
        this.hide();
        this.ventanajugarpor.show();
    }//GEN-LAST:event_cmdVolverActionPerformed

    /**
     * @return
     */

    public PanelImage getLblfigurita1() {
        return lblfigurita1;
    }

    public void setLblfigurita1(PanelImage lblfigurita1) {
        this.lblfigurita1 = lblfigurita1;
    }

    public PanelImage getLblfigurita2() {
        return lblfigurita2;
    }

    public void setLblfigurita2(PanelImage lblfigurita2) {
        this.lblfigurita2 = lblfigurita2;
    }


    public VJUGARPOR getVentanajugarpor() {
        return ventanajugarpor;
    }

    public void setVentanajugarpor(VJUGARPOR ventanajugarpor) {
        this.ventanajugarpor = ventanajugarpor;
    }

    public Figurita getFiguritarepetida() {
        return figuritarepetida;
    }

    public JLabel getLblDificultadRepetido() {
        return lblDificultadRepetido;
    }

    public void setLblDificultadRepetido(JLabel lblDificultadRepetido) {
        this.lblDificultadRepetido = lblDificultadRepetido;
    }

    public JLabel getLblDificultadcanje() {
        return lblDificultadcanje;
    }

    public void setLblDificultadcanje(JLabel lblDificultadcanje) {
        this.lblDificultadcanje = lblDificultadcanje;
    }

    public void setFiguritarepetida(Figurita figuritarepetida) {
        this.figuritarepetida = figuritarepetida;
    }

    public Figurita getFiguritacanje() {
        return figuritacanje;
    }

    public void setFiguritacanje(Figurita figuritacanje) {
        this.figuritacanje = figuritacanje;
    }

    public JComboBox getCboRepetido() {
        return cboRepetido;
    }

    public void setCboRepetido(JComboBox cboRepetido) {
        this.cboRepetido = cboRepetido;
    }

    public JComboBox getCbofaltante() {
        return cbofaltante;
    }

    public void setCbofaltante(JComboBox cbofaltante) {
        this.cbofaltante = cbofaltante;
    }

    public JButton getCmdCanje() {
        return cmdCanje;
    }

    public void setCmdCanje(JButton cmdCanje) {
        this.cmdCanje = cmdCanje;
    }

    public JButton getCmdVolver() {
        return cmdVolver;
    }

    public void setCmdVolver(JButton cmdVolver) {
        this.cmdVolver = cmdVolver;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboRepetido;
    private javax.swing.JComboBox cbofaltante;
    private javax.swing.JButton cmdCanje;
    private javax.swing.JButton cmdVolver;
    private javax.swing.JLabel lblDificultadRepetido;
    private javax.swing.JLabel lblDificultadcanje;
    private org.edisoncor.gui.panel.PanelImage lblfigurita1;
    private org.edisoncor.gui.panel.PanelImage lblfigurita2;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables

    void inicializarventanacanje(VJUGARPOR c) throws ClassNotFoundException, SQLException {
        ventanajugarpor = c;
        ventanajugarpor.hide();
        this.show();
        new FiguritaCanjeController().inicializarCombosCanje(this);


    }
}
