/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jmg.mundial.view;

import com.jmg.mundial.controller.TriviaController;
import com.jmg.mundial.model.Partida;
import com.jmg.mundial.model.Pregunta;

import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class VPREGUNTAS extends javax.swing.JFrame {
    public static Partida part;
    public static Pregunta pregunta;
    public static Object figuritaocombo;
    public static boolean figocom;
    public static VJUGARPOR ini=null;
    
    public VPREGUNTAS() {
        initComponents();
    }
    
    public void iniciarpregunta(Pregunta preguntita, Object figuritaocombo, boolean figocom, Partida parti, VJUGARPOR A)
    {
        VPREGUNTAS.pregunta = preguntita;
        VPREGUNTAS.figocom = figocom;
        VPREGUNTAS.figuritaocombo = figuritaocombo;
        VPREGUNTAS.part = parti;
        VPREGUNTAS.ini = A;
    }

    public JRadioButton getOpcion1() {
        return opcion1;
    }

    public void setOpcion1(String opcion1) {
        this.opcion1.setText(opcion1); ;
    }

    public JRadioButton getOpcion2() {
        return opcion2;
    }

    public void setOpcion2(String opcion2) {
        this.opcion2.setText(opcion2);
    }

    public JRadioButton getOpcion3() {
        return opcion3;
    }

    public void setOpcion3(String opcion3) {
       this.opcion3.setText(opcion3);
    }

    public JRadioButton getOpcion4() {
        return opcion4;
    }

    public void setOpcion4(String opcion4) {
        this.opcion4.setText(opcion4);
    }

    public JRadioButton getOpcion5() {
        return opcion5;
    }

    public void setOpcion5(String opcion5) {
        this.opcion5.setText(opcion5);
    }

    public JTextField getTxtpregunta() {
        return txtpregunta;
    }

    public void setTxtpregunta(String txtpregunta) {
        this.txtpregunta.setText(txtpregunta);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        opcion4 = new javax.swing.JRadioButton();
        opcion5 = new javax.swing.JRadioButton();
        opcion1 = new javax.swing.JRadioButton();
        opcion2 = new javax.swing.JRadioButton();
        txtpregunta = new javax.swing.JTextField();
        cmdResponder = new javax.swing.JButton();
        opcion3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/FIGURAS/TRIVIA.jpg"))); // NOI18N

        opcion4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(opcion4);
        opcion4.setForeground(new java.awt.Color(255, 255, 255));
        opcion4.setText("jRadioButton1");

        opcion5.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(opcion5);
        opcion5.setForeground(new java.awt.Color(255, 255, 255));
        opcion5.setText("jRadioButton1");

        opcion1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(opcion1);
        opcion1.setForeground(new java.awt.Color(255, 255, 255));
        opcion1.setText("jRadioButton1");

        opcion2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(opcion2);
        opcion2.setForeground(new java.awt.Color(255, 255, 255));
        opcion2.setText("jRadioButton1");

        txtpregunta.setEditable(false);
        txtpregunta.setBackground(new java.awt.Color(0, 0, 0));
        txtpregunta.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta.setText("jTextField1");

        cmdResponder.setBackground(new java.awt.Color(255, 51, 51));
        cmdResponder.setText("RESPONDER");
        cmdResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResponderActionPerformed(evt);
            }
        });

        opcion3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(opcion3);
        opcion3.setForeground(new java.awt.Color(255, 255, 255));
        opcion3.setText("jRadioButton1");

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(opcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(cmdResponder)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(txtpregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(opcion5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcion4)
                    .addComponent(cmdResponder))
                .addGap(6, 6, 6)
                .addComponent(opcion1)
                .addGap(3, 3, 3)
                .addComponent(opcion2)
                .addGap(5, 5, 5)
                .addComponent(opcion3)
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResponderActionPerformed
       int control=0;
        if(this.opcion1.isSelected()==true)
      {
          try {
             new TriviaController().verificarrespuesta(part, figocom, figuritaocombo, this.opcion1.getText(), pregunta);
              this.ini.show();
              this.hide();
          
          } catch (  ClassNotFoundException | SQLException ex) {
              Logger.getLogger(VPREGUNTAS.class.getName()).log(Level.SEVERE, null, ex);
          }
          control=1;
      }
       if(this.opcion2.isSelected()==true)
      {
          try {
               new TriviaController().verificarrespuesta(part, figocom, figuritaocombo, this.opcion2.getText(), pregunta);
           this.ini.show();
              this.hide();
          } catch (  ClassNotFoundException | SQLException ex) {
              Logger.getLogger(VPREGUNTAS.class.getName()).log(Level.SEVERE, null, ex);
          }
           control=1;
      }
        if(this.opcion3.isSelected()==true)
      {
          try {
               new TriviaController().verificarrespuesta(part, figocom, figuritaocombo, this.opcion3.getText(), pregunta);
           this.ini.show();
              this.hide();
          } catch (  ClassNotFoundException | SQLException ex) {
              Logger.getLogger(VPREGUNTAS.class.getName()).log(Level.SEVERE, null, ex);
          }
           control=1;
      }
         if(this.opcion4.isSelected()==true)
      {
          try {
               new TriviaController().verificarrespuesta(part, figocom, figuritaocombo, this.opcion4.getText(), pregunta);
          this.ini.show();
              this.hide();
          } catch (  ClassNotFoundException | SQLException ex) {
              Logger.getLogger(VPREGUNTAS.class.getName()).log(Level.SEVERE, null, ex);
          }
           control=1;
      }
          if(this.opcion5.isSelected()==true)
      {
          try {
               new TriviaController().verificarrespuesta(part, figocom, figuritaocombo, this.opcion5.getText(), pregunta);
           this.ini.show();
              this.hide();
          } catch (  ClassNotFoundException | SQLException ex) {
              Logger.getLogger(VPREGUNTAS.class.getName()).log(Level.SEVERE, null, ex);
          }
           control=1;
      }
          if(control==0)
          {
             JOptionPane.showMessageDialog(null, "Debe elegir una respuesta como minimo");
              
          }
    }//GEN-LAST:event_cmdResponderActionPerformed

    /**
     * @param args the command line arguments
   **/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdResponder;
    private javax.swing.JRadioButton opcion1;
    private javax.swing.JRadioButton opcion2;
    private javax.swing.JRadioButton opcion3;
    private javax.swing.JRadioButton opcion4;
    private javax.swing.JRadioButton opcion5;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTextField txtpregunta;
    // End of variables declaration//GEN-END:variables
}
